version: '3'

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ./text:/usr/src/node/text
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  postgres: 
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_DB: postgres